### ISSUE TITLE
[question] unbound did't work for forward.

### ISSUE THREAD

**Issue by KeineK** [coredns/unbound#21]
I am using the unbound plugin of coredns.But unbound didn't work in this conf:
## Corefile
```
.:53 {
    unbound {
       config /root/tmp/unbound.conf
    }
    log
    cache {
         success 10240 1800 
         denial 2500 600
         prefetch 8000
    }
    health :8090
    errors
    whoami
}
```

## unbound.conf
```
forward-zone:
    name: "."
    forward-addr: 8.8.8.8
```
But when i get a record, it say:
```
$ dig www.google.com @localhost

; <<>> DiG 9.10.3-P4-Debian <<>> www.google.com @localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 57794
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ADDITIONAL SECTION:
www.google.com.         5       IN      A       172.17.0.1
_udp.www.google.com.    5       IN      SRV     0 0 33089 .

;; Query time: 1 msec
;; SERVER: ::1#53(::1)

;; MSG SIZE  rcvd: 111
```
~~~  WARNING: recursion requested but not available. ~~~
And coredns log it:
```
[INFO] 172.17.0.1:33089 - 57794 "A IN www.google.com. udp 43 false 4096" NOERROR qr,aa,rd 100 0.000150929s
```
Coredns had loaded the unbound.conf,but i think the unbound didn't work well. So how can i make it work?

**Comment by tomsanbear** [comment]
From an initial look at your DNS query, seems to me that the whoami plugin is overriding the configuration for your server. Ordering is defined by the plugin.cfg during compile of coredns, and likely you placed the unbound plugin below the whoami plugin.

The below config with the whoami removed should work.

## Corefile
```
.:53 {
    unbound {
       config /root/tmp/unbound.conf
    }
    log
    cache {
         success 10240 1800 
         denial 2500 600
         prefetch 8000
    }
    health :8090
    errors
}
```

**Comment by KeineK** [comment]
> From an initial look at your DNS query, seems to me that the whoami plugin is overriding the configuration for your server. Ordering is defined by the plugin.cfg during compile of coredns, and likely you placed the unbound plugin below the whoami plugin.
> 
> The below config with the whoami removed should work.
> ## Corefile
> 
> ```
> .:53 {
>     unbound {
>        config /root/tmp/unbound.conf
>     }
>     log
>     cache {
>          success 10240 1800 
>          denial 2500 600
>          prefetch 8000
>     }
>     health :8090
>     errors
> }
> ```

It works now.Thanks for your help !
