### ISSUE TITLE
Update refs to mholt/caddy -> caddyserver/caddy

### ISSUE THREAD

**Issue by fuhry** [coredns/unbound#22]
```
setup.go:24:21: cannot use c (type *"github.com/mholt/caddy".Controller) as type *"github.com/caddyserver/caddy".Controller in argument to dnsserver.GetConfig
```

**Comment by miekg** [comment]
ah, yes, please send pr; forgot about this one

**Comment by fuhry** [comment]
Hey @miekg, thanks for your very quick response. One question before I submit the PR... my local branch is not building currently because unbound uses coredns v1.4.0 which has the same issue of mholt/caddy being renamed to mholt/caddyserver. I updated to coredns v1.6.3 and that's refusing to build because of a downstream dependency. At coredns v1.5.0 everything does build.

Shall I:

1. Limit this PR to fixing the caddyserver references and let the coredns dep get sorted out later,
2. Update to coredns v1.5.0 since that's in a buildable state, or
3. Update to `coredns@latest` and expect that its downstream dependency (etcd) gets figured out eventually?

I'm pretty new to go and working with it mostly in a devops capacity at my current job, so please excuse me if I'm misunderstanding anything.

**Comment by miekg** [comment]
why is 1.6.3 not building? It's building when you just build coredns by itself, so that should just work...?

**Comment by fuhry** [comment]
I'm currently receiving this trivial but frustrating dependency issue:

```
GOPATH/src/github.com/fuhry/unbound $ go version
go version go1.13 linux/amd64
GOPATH/src/github.com/fuhry/unbound $ go get github.com/coredns/coredns@latest
go get: github.com/coredns/coredns@v1.6.3 requires
        go.etcd.io/etcd@v0.0.0-20190823073701-67d0c21bb04c requires
        golang.org/x/net@v0.0.0-20190813000000-74dc4d7220e7: invalid pseudo-version: does not match version-control timestamp (2019-08-13T14:13:03Z)
```

**Comment by miekg** [comment]
Oh ffs, go modules shenigans. I'll try to take a look
