### ISSUE TITLE
Unbound plugin not producing log or DNSTAP events

### ISSUE THREAD

**Issue by SuperFunks** [coredns/unbound#26]
It seems like the external unbound plugin doesn't play well with other plugins like log and dnstap.

```
. {
        unbound
        cache 604800 {
                prefetch 5 60m 10%
        }
        log
        dnstap tcp://127.0.0.1:6000 full
        prometheus :9252
}
```

When this configuration is hit - no log or dnstap events are generated - even though the DNSTAP connection is established.
Is the configuration wrong?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[coredns/unbound] Unbound plugin no..." ]
>It seems like the external unbound plugin doesn't play well with other plugins
>like log and dnstap.
>
>. {
>unbound
>cache 604800 {
>prefetch 5 60m 10%
>}
>log
>dnstap tcp://127.0.0.1:6000 full
>prometheus :9252
>}
>
>When this configuration is hit - no log or dnstap events are generated - even
>though the DNSTAP connection is established.
>Is the configuration wrong?

depends on your plugin.cfg if unbound is before those plugins, then yes

**Comment by SuperFunks** [comment]
Sorry - my bad :) - works flawlessly now with unbound being last in the plugin chain.

Thanks again @miekg - you rock!
